[versions]
agp = "8.12.0"
camera = "1.5.2"
detekt = "1.23.8"
hilt = "2.57.2"
hiltAndroidx = "1.3.0"
kotlin = "2.2.21"
ktor = "3.3.3"
lifecycle = "2.10.0"
navCompose = "2.9.6"
room = "2.8.4"
slf4j = "2.0.17"
haze = "1.7.1"

[libraries]
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version = "0.36.0" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version = "0.37.3" }
activity-compose = { module = "androidx.activity:activity-compose", version = "1.12.1" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version = "17.3.0" }
biometric = { module = "androidx.biometric:biometric", version = "1.4.0-alpha04" }
bitkit-core = { module = "com.synonym:bitkit-core-android", version = "0.1.30" }
bouncycastle-provider-jdk = { module = "org.bouncycastle:bcprov-jdk18on", version = "1.83" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }
# https://developer.android.com/develop/ui/compose/bom/bom-mapping
compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2025.12.00" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.1.1" }
core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version = "1.2.0" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version = "1.2.0" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-compose-rules = { module = "io.nlopez.compose.rules:detekt", version = "0.5.0" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version = "34.6.0" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltAndroidx" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltAndroidx" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltAndroidx" }
jna = { module = "net.java.dev.jna:jna", version = "5.18.1" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.7.1" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
#ldk-node-android = { module = "org.lightningdevkit:ldk-node-android", version = "0.7.0" } # upstream
#ldk-node-android = { module = "org.lightningdevkit:ldk-node-android", version = "0.7.0" } # local
ldk-node-android = { module = "com.github.synonymdev:ldk-node", version = "v0.7.0" } # fork
lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version = "1.13.0" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navCompose" }
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navCompose" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
test-core = { module = "androidx.test:core", version = "1.7.0" }
test-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test" }
test-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.7.0" }
test-junit = { group = "junit", name = "junit", version = "4.13.2" }
test-junit-ext = { module = "androidx.test.ext:junit", version = "1.3.0" }
test-mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "6.1.0" }
test-robolectric = { module = "org.robolectric:robolectric", version = "4.16" }
test-turbine = { group = "app.cash.turbine", name = "turbine", version = "1.2.1" }
vss = { module = "com.synonym:vss-client-android", version = "0.3.0" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version = "2.11.0" }
zxing = { module = "com.google.zxing:core", version = "3.5.4" }
lottie = { module = "com.airbnb.android:lottie-compose", version = "6.7.1" }
charts = { module = "io.github.ehsannarmani:compose-charts", version = "0.2.0" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
google-services = { id = "com.google.gms.google-services", version = "4.4.4" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.3.2" }
room = { id = "androidx.room", version.ref = "room" }
